name: newyork-taxi-fare-prediction

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10.6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - transformers
  - python-dotenv
  - autopep8
  - pylint
  - ipykernel
  - streamlit
  - fastapi
  - pip
  - pip:
      - timm
      - torch 
      - torchvision 
      - torchaudio