name: pdf-query-bot
channels:
  - conda-forge
  - defaults

dependencies:
  - ipykernel

  - pip:
      - langchain
      - openai
      - PyPDF2
      - python-dotenv
      - faiss-cpu
      - langchain-community
      - tiktoken